namespace SensorApp.Models;

public class Alert
{
    public int Id { get; set; }
    public int DeviceId { get; set; }
    public DateTime Timestamp { get; set; }
    public double Value { get; set; }
    public double Threshold { get; set; }
    public double? AverageValue { get; set; }
    public string Message { get; set; } = string.Empty;
    public bool IsAutoGenerated { get; set; }

    public Device Device { get; set; } = null!;
}
