using SensorApp.Dtos;
using SensorApp.Models;

namespace SensorApp.Services;

public static class LegacyDtoMapper
{
    private const int ReadingType = 1;
    private const int AlertType = 3;

    public static LegacyDataDto FromReading(SensorReading reading) => new()
    {
        Id = reading.Id,
        Did = reading.DeviceId,
        Ts = FormatTimestamp(reading.Timestamp),
        V = reading.Temperature,
        V2 = reading.Humidity,
        V3 = reading.Pressure,
        Typ = ReadingType,
        St = (int)reading.Status,
        Flg = 0,
        N = string.Empty
    };

    public static LegacyDataDto FromAlert(Alert alert) => new()
    {
        Id = alert.Id,
        Did = alert.DeviceId,
        Ts = FormatTimestamp(alert.Timestamp),
        V = alert.Value,
        V2 = alert.AverageValue ?? alert.Threshold,
        V3 = 0,
        Typ = AlertType,
        St = (int)DeviceStatus.Active,
        Flg = alert.IsAutoGenerated ? 1 : 0,
        N = alert.Message
    };

    public static LegacyDataDto FromDevice(Device device) => new()
    {
        Id = device.Id,
        Nm = device.Name,
        Loc = device.Location,
        Tp = (int)device.SensorType,
        St = (int)device.Status,
        Cfg = DeviceConfigFormatter.ToLegacyConfig(device),
        Ts = FormatTimestamp(device.UpdatedAt),
        V = device.Threshold,
        V2 = device.ReportingIntervalSeconds
    };

    public static LegacyDataDto FromAuditLog(AuditLog log) => new()
    {
        Id = log.Id,
        Did = log.DeviceId ?? 0,
        N = log.Message,
        Ts = FormatTimestamp(log.Timestamp),
        Flg = log.IsAlert ? 1 : 0
    };

    public static string FormatTimestamp(DateTime timestamp) =>
        timestamp.ToString("yyyy-MM-dd HH:mm:ss");
}
